# Generated by Django 4.2.6 on 2023-10-19 10:00

import app001.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to=app001.models.upload_to_post_images),
        ),
    ]
